/*******************************************************************************
 *                                                                             *
 * This image definition file is generated by FontGen v1.72                    *
 *              by Bahri Okuroglu - bahrio@yahoo.com                           *
 *                                                                             *
 * Make sure it is legal to use images on your PC for this conversion          *
 *                                                                             *
 * Image definition for file \\192.168.1.2\public\Karat\Kasa\Fonts\splash_logo.bmp
 *                                                                             *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' *
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,       *
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR      *
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR          *
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,       *
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,         *
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; *
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,    *
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR     *
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF      *
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE                                   *
 *******************************************************************************/


#ifndef FONTGEN_ITYPES
#define FONTGEN_ITYPES

typedef struct IMG_DEF {
   unsigned short width;     /* Image width */
   unsigned char height;    /* Image height*/
   unsigned char const *char_table;         /* Image table start address in memory  */
} IMG_DEF;
#endif

extern struct IMG_DEF const splash_screen;


